import Head from 'next/head';
import Link from 'next/link';
import React from 'react';

export default function Layout({ title, children }) {
  return (
    <>
      <Head>
        <title>{title ? title + ' - Amazona' : 'Amazona'}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex min-h-screen flex-col justify-between">
        <header>
          <nav className="flex justify-between h-12 shadow-lg items-center px-4 ">
            <Link href="/">Amazona</Link>
            <div>
              <Link href="cart" className="p-2">
                Cart
              </Link>
              <Link href="login" className="p-2">
                Login
              </Link>
            </div>
          </nav>
        </header>
        <main className="container mt-4 m-auto ">{children}</main>
        <footer className="flex justify-center items-center h-12 shadow-inner">
          footer
        </footer>
      </div>
    </>
  );
}
